apiVersion: v1
kind: Service
metadata:
  name: elector
  namespace: kubeflow
  labels:
    run: elector
spec:
  type: NodePort
  ports:
  - name: http
    port: 5002
    targetPort: 5002
    protocol: TCP
  selector:
    run: elector